(in-package #:noloop.cacau)

(defun reporter-full (runner options)
  (cacau-logo)
  (when (or (some #'(lambda (i) (equal :tests-list i)) options)
            (null options))
    (suite-tests-list-events runner))
  (lambda ()
    (inspect (result runner))
    ;; (if (null options)
    ;;     (full-epilogue (result runner) nil)
    ;;     (dolist (i options)
    ;;       (when (listp i)
    ;;         (when (equal :epilogue (first i))
    ;;           (full-epilogue (result runner) (second i))))))
    ;; (when (or (some #'(lambda (i) (equal :stack i)) options)
    ;;           (null options))
    ;;   (inspect (result runner))
    ;;   (stack-test-errors (result runner)))
    ))

